### ISSUE TITLE
Erro Instalação

### ISSUE THREAD

**Issue by marceloengecom** [ATSTI/odoo_boleto#1]
Primeiramente, gostaria de agradecer a tua contribuição. É módulo bastante útil para o Odoo v8.

Sobre o problema, está ocorrendo quando tento instalar o módulo.

A mensagem que aparece é:

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 941, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 143, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/openerp/modules/module.py", line 315, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/opt/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/localizacao/odoo_boleto/boleto/**init**.py", line 22, in <module>
    import wizard
  File "/opt/odoo/localizacao/odoo_boleto/boleto/wizard/**init**.py", line 19, in <module>
    import boleto_create
  File "/opt/odoo/localizacao/odoo_boleto/boleto/wizard/boleto_create.py", line 25, in <module>
    from pyboleto.bank.sicredi import BoletoSicredi
ImportError: No module named sicredi

Acredito que seja algo relacionado a adição do banco Sicredi.

Caso possa ajudar, agradeço.

Abraço,
Marcelo

**Comment by ATSTI** [comment]
Veja no pyboleto que está aqui, ali tem o sicredi.py.

**Comment by amostech** [comment]
Nao estou conseguindo utilizar o modulo pyboleto que está aqui no github. Eu percebi que está incluido sim o novo banco o sicredi.py, mas nao tenho como instalar esse pyboleto que está aqui pois não há o arquivo setup.py.

O que estou fazendo errado?

**Comment by crsilveira** [comment]
Me desculpe, fiz a correção, e está aqui :  https://github.com/crsilveira/pyboleto
